function result = example_main_case()
%EXAMPLE_MAIN_CASE Small, readable example of the new workflow.
%   result = EXAMPLE_MAIN_CASE()
%
% This example trims the aircraft at 70 m/s using the saved Homework 7
% trim table, seeds the main plant to that operating point, and then asks
% for a small elevator step. If the main run model still has unresolved
% Simulink issues, run_main_case will stop with a clear diagnostic after
% the trim context and workspace have already been prepared.

trimSpec = struct( ...
    'source', 'saved', ...
    'cruiseSpeedMps', 70, ...
    'bankDeg', 0, ...
    'tiltAnglesGrouped', [90; 90]);

runSpec = struct( ...
    'name', 'saved trim with small elevator step', ...
    'stopTime', 8.0, ...
    'stepTime', 1.0, ...
    'deltaEStep', deg2rad(1.0));

result = run_main_case('TrimSpec', trimSpec, 'RunSpec', runSpec);
disp(result.summary);
end
