function runCtx = adapt_trim_to_run_model(session, trimCtx, runSpec)
%ADAPT_TRIM_TO_RUN_MODEL Map canonical trim data onto the main run model.

runSpec = default_run_spec_main(runSpec);

surfaceInit = localMixSurfaceInitialStates(trimCtx.surface_deflections);

runCtx = struct();
runCtx.repoRoot = session.repoRoot;
runCtx.runModel = session.runModel;
runCtx.stopTime = runSpec.stopTime;
runCtx.stepTime = runSpec.stepTime;
runCtx.runSimulation = logical(runSpec.runSimulation);
runCtx.inputConvention = char(runSpec.inputConvention);
runCtx.useAvlAero = logical(runSpec.useAvlAero);
runCtx.trimCtx = trimCtx;
runCtx.commands = struct();
runCtx.commands.grouped = struct( ...
    'motor_rpm_cmd', trimCtx.motor_rpm_cmd_grouped(:), ...
    'tilt_angles_cmd', trimCtx.tilt_angles_grouped(:));
runCtx.commands.legacy = struct( ...
    'motor_rpm_cmd', localExpandMotorCommand(trimCtx.motor_rpm_cmd_grouped), ...
    'tilt_angles_cmd', localExpandTiltGrouped(trimCtx.tilt_angles_grouped));
runCtx.commands.front_collective_rpm = trimCtx.collectives.front_rpm;
runCtx.commands.rear_collective_rpm = trimCtx.collectives.rear_rpm;
runCtx.commands.delta_f = trimCtx.surface_deflections.delta_f;
runCtx.commands.delta_a = trimCtx.surface_deflections.delta_a;
runCtx.commands.delta_e = trimCtx.surface_deflections.delta_e;
runCtx.commands.delta_r = trimCtx.surface_deflections.delta_r;

runCtx.stepCommands = struct( ...
    'motor_rpm_cmd', runSpec.motorRPMCmdStepGrouped(:), ...
    'tilt_angles_cmd', runSpec.tiltStepGrouped(:), ...
    'front_collective_rpm', runSpec.frontCollectiveStep, ...
    'rear_collective_rpm', runSpec.rearCollectiveStep, ...
    'delta_f', runSpec.deltaFStep, ...
    'delta_a', runSpec.deltaAStep, ...
    'delta_e', runSpec.deltaEStep, ...
    'delta_r', runSpec.deltaRStep);

runCtx.plantInitial = struct( ...
    'pos_init', trimCtx.pos(:), ...
    'V_init', trimCtx.vel_body(:), ...
    'eul_init', trimCtx.euler(:), ...
    'omega_init', trimCtx.omega_body(:), ...
    'quat_init', localEulerToQuat(trimCtx.euler(:)));

runCtx.actuatorInitial = struct( ...
    'motor_rpms_grouped', trimCtx.motor_rpms_grouped(:), ...
    'tilt_angles_grouped', trimCtx.tilt_angles_grouped(:), ...
    'surface_physical', surfaceInit);

runCtx.workspaceAssignments = struct( ...
    'pos_init', trimCtx.pos(:), ...
    'V_init', trimCtx.vel_body(:), ...
    'eul_init', trimCtx.euler(:), ...
    'omega_init', trimCtx.omega_body(:), ...
    'quat_init', localEulerToQuat(trimCtx.euler(:)), ...
    'Motor_RPMs', trimCtx.motor_rpms_grouped(:), ...
    'Tilt_angles', trimCtx.tilt_angles_grouped(:), ...
    'controller_trim_motor_rpms', zeros(4, 1), ...
    'controller_trim_tilt_angles', trimCtx.tilt_angles_grouped(:), ...
    'controller_trim_motor_rpm_cmd', trimCtx.motor_rpm_cmd_grouped(:), ...
    'controller_trim_tilt_angles_cmd', trimCtx.tilt_angles_grouped(:), ...
    'controller_trim_delta_f', trimCtx.surface_deflections.delta_f, ...
    'controller_trim_delta_a', trimCtx.surface_deflections.delta_a, ...
    'controller_trim_delta_e', trimCtx.surface_deflections.delta_e, ...
    'controller_trim_delta_r', trimCtx.surface_deflections.delta_r, ...
    'controller_airspeed_cmd_base', trimCtx.vinf, ...
    'controller_bank_cmd_base', trimCtx.euler(1), ...
    'trim_front_collective_rpm', trimCtx.collectives.front_rpm, ...
    'trim_rear_collective_rpm', trimCtx.collectives.rear_rpm, ...
    'estimator_init_eul', trimCtx.euler(:), ...
    'use_avl_aero', logical(runSpec.useAvlAero));

runCtx.surfaceInitial = surfaceInit;
runCtx.name = runSpec.name;
end

function surfaceInit = localMixSurfaceInitialStates(surfaceDeflections)
surfaceInit = struct();
surfaceInit.wingL = surfaceDeflections.delta_f + surfaceDeflections.delta_a;
surfaceInit.wingR = surfaceDeflections.delta_f - surfaceDeflections.delta_a;
surfaceInit.tailL = surfaceDeflections.delta_e - surfaceDeflections.delta_r;
surfaceInit.tailR = surfaceDeflections.delta_e + surfaceDeflections.delta_r;
end

function motorCmdLegacy = localExpandMotorCommand(groupedMotorCmd)
groupedMotorCmd = groupedMotorCmd(:);
if numel(groupedMotorCmd) < 4
    groupedMotorCmd = groupedMotorCmd(1) * ones(4, 1);
end
motorCmdLegacy = [ ...
    groupedMotorCmd(2) * ones(3, 1); ...
    groupedMotorCmd(1) * ones(3, 1); ...
    groupedMotorCmd(4) * ones(3, 1); ...
    groupedMotorCmd(3) * ones(3, 1)];
end

function tiltLegacy = localExpandTiltGrouped(groupedTilt)
groupedTilt = groupedTilt(:);
if numel(groupedTilt) < 2
    groupedTilt = groupedTilt(1) * ones(2, 1);
end
tiltLegacy = [groupedTilt(1) * ones(3, 1); groupedTilt(2) * ones(3, 1)];
end

function quat = localEulerToQuat(eulerAngles)
phi = eulerAngles(1);
theta = eulerAngles(2);
psi = eulerAngles(3);

cy = cos(psi * 0.5);
sy = sin(psi * 0.5);
cp = cos(theta * 0.5);
sp = sin(theta * 0.5);
cr = cos(phi * 0.5);
sr = sin(phi * 0.5);

quat = [ ...
    cr * cp * cy + sr * sp * sy; ...
    sr * cp * cy - cr * sp * sy; ...
    cr * sp * cy + sr * cp * sy; ...
    cr * cp * sy - sr * sp * cy];
end
