function prepOptions = build_corridor_test_preset(routeName)
%BUILD_TRANSITION_CORRIDOR_TEST_PRESET
% Shared preset factory for active transition corridor controller cases.
%
% Supported names:
%   current_best
%   highbridge_ultra_120
%   highbridge_ultra_240
%   high_ultra_120
%   mid_ultra_120
%   low_ultra_120
%   highbridge / high / mid / low

if nargin < 1 || isempty(routeName)
    routeName = 'current_best';
end

routeName = lower(string(routeName));
[routeName, namedStopTime_s] = localResolvePreset(routeName);
[guideV, guideT] = localGuide(routeName);

prepOptions = struct();
prepOptions.scheduler_mode = 'global_ramp';
prepOptions.run_stop_time_s = namedStopTime_s;
prepOptions.controller_opts = struct( ...
    'selector_opts', struct( ...
        'guide_vinf_mps', guideV, ...
        'guide_tilt_deg', guideT, ...
        'waypoint_search_vinf_mps', 10.0, ...
        'waypoint_search_tilt_deg', 10.0, ...
        'max_candidates_per_waypoint', 16, ...
        'max_delta_vinf_per_step', 12.5, ...
        'max_delta_tilt_per_step', 15.0, ...
        'rear_floor_min_rpm', 400.0, ...
        'rear_floor_max_vinf_mps', 45.0, ...
        'rear_floor_max_tilt_deg', 75.0, ...
        'edge_weight_rear_drop_rpm', 2.5, ...
        'max_rear_drop_rpm_per_step', 450.0, ...
        'point_weight_abs_delta_f_deg', 0.60, ...
        'point_weight_abs_delta_e_deg', 0.60, ...
        'point_weight_abs_theta_deg', 1.10, ...
        'max_abs_delta_f_deg', 18.0, ...
        'max_abs_delta_e_deg', 18.0, ...
        'max_abs_theta_deg', 35.0, ...
        'plot_result', true, ...
        'show_popup', true), ...
    'gating_opts', struct( ...
        'settle_theta_deg', 2.5, ...
        'settle_u_mps', 0.75, ...
        'settle_w_mps', 0.75, ...
        'settle_q_deg_s', 2.5, ...
        'settle_time_s', 1.5, ...
        'segment_ramp_time_s', 6.0), ...
    'lqr_opts', struct( ...
        'Q_long', diag([12.0, 1.20, 3.20, 5.00]), ...
        'R_long', diag([0.45, 0.70, 3200.0, 2600.0])));
prepOptions.schedule_opts = struct( ...
    'direction', 'hover_to_cruise', ...
    'step_time_s', 0.01, ...
    'stop_time_s', namedStopTime_s, ...
    'hold_start_s', 8.0, ...
    'hold_end_s', 8.0, ...
    'command_anchor_source', 'guide');

if routeName == "highbridge"
    prepOptions.controller_opts.selector_opts.max_candidates_per_waypoint = 40;
    prepOptions.controller_opts.selector_opts.max_delta_vinf_per_step = 17.5;
end
end

function [routeName, stopTime_s] = localResolvePreset(routeName)
stopTime_s = 120.0;

switch routeName
    case "current_best"
        routeName = "highbridge";
        stopTime_s = 240.0;
    case "highbridge_ultra_240"
        routeName = "highbridge";
        stopTime_s = 240.0;
    case "highbridge_ultra_120"
        routeName = "highbridge";
    case "high_ultra_120"
        routeName = "high";
    case "mid_ultra_120"
        routeName = "mid";
    case "low_ultra_120"
        routeName = "low";
    otherwise
        % Keep direct route names working.
end
end

function [guideV, guideT] = localGuide(routeName)
guideV = [0 2.5 5 10 15 20 25 30 40 50 60 70];
switch routeName
    case "low"
        guideT = [0 8 15 27.5 40 50 57.5 65 75 82.5 87.5 90];
        guideV = [0 2.5 5 10 15 20 25 30 40 50 60 70];
    case "highbridge"
        guideV = [0 2.5 5 7.5 20 25 35 50 55 62.5 70];
        guideT = [0 10 25 37.5 52.5 55 65 70 85 87.5 90];
    case "high"
        guideT = [0 12.5 25 45 57.5 65 70 75 80 84 87.5 90];
        guideV = [0 2.5 5 10 15 20 25 30 40 50 60 70];
    otherwise
        guideT = [0 10 22 35 47.5 55 62.5 67.5 78 83 87 90];
        guideV = [0 2.5 5 10 15 20 25 30 40 50 60 70];
end
end
